#!/usr/bin/env zsh

set_git_config() {
  local label="$1"
  local config_key="$2"
  local current_value=$(git config --global "$config_key")
  local input_value

  echo -en "${YELLOW}What's your $label? ${NC}[$current_value] "
  read input_value </dev/tty

  git config --global "$config_key" "${input_value:-$current_value}"
}

echo ""
set_git_config "name" "user.name"
set_git_config "email" "user.email"